[package]
name = "sardumper"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
object = "0.36.5"
thiserror = "2.0.7"

[dependencies.windows]
version = "0.58.0"
features = [
    "Win32_System_LibraryLoader",
    "Win32_System_ProcessStatus",
    "Win32_System_Threading"
]
